
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
    modId="hyperdaimc" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="§6§oHyperlink" #mandatory
    # A URL for the "homepage" for this mod, displayed in the mod UI
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    logoFile="hyperlink.png" #optional
    credits='''

[効果音]
    [素材]
        効果音ラボ 様
        効果音ラボ https://soundeffect-lab.info

        小森平 様
        無料効果音で遊ぼう！ https://taira-komori.jpn.org/index.html
    [編集]
        窓の杜 様
        Audacity https://forest.watch.impress.co.jp/library/software/audacity
''' #optional
    authors="Sakurafuld" #optional
    description='''神の恵みを受け取れぇ！''' #mandatory

[[dependencies.hyperdaimc]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.hyperdaimc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hyperdaimc]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.2-5.0.9.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.hyperdaimc]]
    modId="integratedtunnels"
    mandatory=false
    versionRange="[1.8.22,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.hyperdaimc]]
    modId="mekanism"
    mandatory=false
    versionRange="[10.2.5,)"
    ordering="AFTER"
    side="BOTH"